// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUiTest.Test
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = Microsoft.VisualStudio.TestTools.UITest.Input.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        #region Properties
        public UIStartWindow UIStartWindow
        {
            get
            {
                if ((this.mUIStartWindow == null))
                {
                    this.mUIStartWindow = new UIStartWindow();
                }
                return this.mUIStartWindow;
            }
        }
        
        public UICodedUItestWindow UICodedUItestWindow
        {
            get
            {
                if ((this.mUICodedUItestWindow == null))
                {
                    this.mUICodedUItestWindow = new UICodedUItestWindow();
                }
                return this.mUICodedUItestWindow;
            }
        }
        
        public UICodedUItestWindow1 UICodedUItestWindow1
        {
            get
            {
                if ((this.mUICodedUItestWindow1 == null))
                {
                    this.mUICodedUItestWindow1 = new UICodedUItestWindow1();
                }
                return this.mUICodedUItestWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIStartWindow mUIStartWindow;
        
        private UICodedUItestWindow mUICodedUItestWindow;
        
        private UICodedUItestWindow1 mUICodedUItestWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIStartWindow : XamlWindow
    {
        
        public UIStartWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "Start";
            this.SearchProperties[XamlControl.PropertyNames.ClassName] = "Windows.UI.Core.CoreWindow";
            this.WindowTitles.Add("Start");
            #endregion
        }
        
        #region Properties
        public UIAppsviewList UIAppsviewList
        {
            get
            {
                if ((this.mUIAppsviewList == null))
                {
                    this.mUIAppsviewList = new UIAppsviewList(this);
                }
                return this.mUIAppsviewList;
            }
        }
        #endregion
        
        #region Fields
        private UIAppsviewList mUIAppsviewList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAppsviewList : XamlList
    {
        
        public UIAppsviewList(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlList.PropertyNames.AutomationId] = "AppsList";
            this.WindowTitles.Add("Start");
            #endregion
        }
        
        #region Properties
        public UICGroup UICGroup
        {
            get
            {
                if ((this.mUICGroup == null))
                {
                    this.mUICGroup = new UICGroup(this);
                }
                return this.mUICGroup;
            }
        }
        #endregion
        
        #region Fields
        private UICGroup mUICGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UICGroup : XamlControl
    {
        
        public UICGroup(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Group";
            this.SearchProperties[UITestControl.PropertyNames.Name] = "C";
            this.WindowTitles.Add("Start");
            #endregion
        }
        
        #region Properties
        public XamlListItem UICodedUItestNewListItem
        {
            get
            {
                if ((this.mUICodedUItestNewListItem == null))
                {
                    this.mUICodedUItestNewListItem = new XamlListItem(this);
                    #region Search Criteria
                    this.mUICodedUItestNewListItem.SearchProperties[XamlListItem.PropertyNames.AutomationId] = "44c5756c-9fed-4add-bca4-252fbdffa171_gecswmz8y675e!App";
                    this.mUICodedUItestNewListItem.WindowTitles.Add("Start");
                    #endregion
                }
                return this.mUICodedUItestNewListItem;
            }
        }
        #endregion
        
        #region Fields
        private XamlListItem mUICodedUItestNewListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UICodedUItestWindow : UITestControl
    {
        
        public UICodedUItestWindow()
        {
            #region Search Criteria
            this.TechnologyName = "UIA";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Window";
            this.SearchProperties[UITestControl.PropertyNames.Name] = "CodedUItest";
            this.SearchProperties["FrameworkId"] = "Win32";
            #endregion
        }
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UICodedUItestWindow1 : XamlWindow
    {
        
        public UICodedUItestWindow1()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "CodedUItest";
            this.SearchProperties[XamlControl.PropertyNames.ClassName] = "Windows.UI.Core.CoreWindow";
            this.WindowTitles.Add("CodedUItest");
            #endregion
        }
        
        #region Properties
        public XamlButton UIOrderButton
        {
            get
            {
                if ((this.mUIOrderButton == null))
                {
                    this.mUIOrderButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIOrderButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "OrderButton";
                    this.mUIOrderButton.WindowTitles.Add("CodedUItest");
                    #endregion
                }
                return this.mUIOrderButton;
            }
        }
        
        public UIPersonsListList UIPersonsListList
        {
            get
            {
                if ((this.mUIPersonsListList == null))
                {
                    this.mUIPersonsListList = new UIPersonsListList(this);
                }
                return this.mUIPersonsListList;
            }
        }
        #endregion
        
        #region Fields
        private XamlButton mUIOrderButton;
        
        private UIPersonsListList mUIPersonsListList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIPersonsListList : XamlList
    {
        
        public UIPersonsListList(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlList.PropertyNames.AutomationId] = "PersonsList";
            this.WindowTitles.Add("CodedUItest");
            #endregion
        }
        
        #region Properties
        public UICodedUItestPersonListItem UICodedUItestPersonListItem
        {
            get
            {
                if ((this.mUICodedUItestPersonListItem == null))
                {
                    this.mUICodedUItestPersonListItem = new UICodedUItestPersonListItem(this);
                }
                return this.mUICodedUItestPersonListItem;
            }
        }
        
        public XamlButton UICREATEButton
        {
            get
            {
                if ((this.mUICREATEButton == null))
                {
                    this.mUICREATEButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUICREATEButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "CreateButton";
                    this.mUICREATEButton.WindowTitles.Add("CodedUItest");
                    #endregion
                }
                return this.mUICREATEButton;
            }
        }
        
        public UICodedUItestPersonListItem1 UICodedUItestPersonListItem1
        {
            get
            {
                if ((this.mUICodedUItestPersonListItem1 == null))
                {
                    this.mUICodedUItestPersonListItem1 = new UICodedUItestPersonListItem1(this);
                }
                return this.mUICodedUItestPersonListItem1;
            }
        }
        
        public UICodedUItestPersonListItem2 UICodedUItestPersonListItem2
        {
            get
            {
                if ((this.mUICodedUItestPersonListItem2 == null))
                {
                    this.mUICodedUItestPersonListItem2 = new UICodedUItestPersonListItem2(this);
                }
                return this.mUICodedUItestPersonListItem2;
            }
        }
        #endregion
        
        #region Fields
        private UICodedUItestPersonListItem mUICodedUItestPersonListItem;
        
        private XamlButton mUICREATEButton;
        
        private UICodedUItestPersonListItem1 mUICodedUItestPersonListItem1;
        
        private UICodedUItestPersonListItem2 mUICodedUItestPersonListItem2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UICodedUItestPersonListItem : XamlListItem
    {
        
        public UICodedUItestPersonListItem(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlListItem.PropertyNames.Name] = "CodedUItest.Person";
            this.SearchProperties[XamlListItem.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("CodedUItest");
            #endregion
        }
        
        #region Properties
        public XamlButton UIPressButton
        {
            get
            {
                if ((this.mUIPressButton == null))
                {
                    this.mUIPressButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIPressButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "Test";
                    this.mUIPressButton.WindowTitles.Add("CodedUItest");
                    #endregion
                }
                return this.mUIPressButton;
            }
        }
        #endregion
        
        #region Fields
        private XamlButton mUIPressButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UICodedUItestPersonListItem1 : XamlListItem
    {
        
        public UICodedUItestPersonListItem1(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlListItem.PropertyNames.Name] = "CodedUItest.Person";
            this.SearchProperties[XamlListItem.PropertyNames.Instance] = "12";
            this.WindowTitles.Add("CodedUItest");
            #endregion
        }
        
        #region Properties
        public XamlButton UIPressButton
        {
            get
            {
                if ((this.mUIPressButton == null))
                {
                    this.mUIPressButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIPressButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "Joakim";
                    this.mUIPressButton.WindowTitles.Add("CodedUItest");
                    #endregion
                }
                return this.mUIPressButton;
            }
        }
        #endregion
        
        #region Fields
        private XamlButton mUIPressButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UICodedUItestPersonListItem2 : XamlListItem
    {
        
        public UICodedUItestPersonListItem2(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlListItem.PropertyNames.Name] = "CodedUItest.Person";
            this.SearchProperties[XamlListItem.PropertyNames.Instance] = "11";
            this.WindowTitles.Add("CodedUItest");
            #endregion
        }
        
        #region Properties
        public XamlButton UIPressButton
        {
            get
            {
                if ((this.mUIPressButton == null))
                {
                    this.mUIPressButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIPressButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "Jan";
                    this.mUIPressButton.WindowTitles.Add("CodedUItest");
                    #endregion
                }
                return this.mUIPressButton;
            }
        }
        #endregion
        
        #region Fields
        private XamlButton mUIPressButton;
        #endregion
    }
}
